# Name of action
name: Android Build

# When the workflow is run? - on a PR
on: pull_request

#Tasks to be run on each PR
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      # Assemble our project
      - name: Build Project
        run: ./gradlew assemble